// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Robot alien":return img`
..............................
..............................
..........44444444............
........444ffffff44...........
........44ff1111ff44...ff.....
.......44ff111111ff4..fff.....
.......44fd11ffd11f4.fff......
.......44fd11fff11f4fff.......
....ffff4fd11fff11f4ff........
....ffff4fddd1111ff4f.........
....ff.44ffddddddf44..........
...fff.444fffddfff44..........
...fff..4444ffff444...........
.........444444444............
..........4444444f............
..........ff....ff............
..........fffff.ffff..........
..........fffff.ffff..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
